//>>built
define("gridx/modules/ColumnLock","dojo/dom-style dojo/dom-class dojo/dom-geometry dojo/_base/lang ../core/_Module dojo/_base/declare dojo/_base/array dojo/_base/window dojo/query dojo/_base/sniff".split(" "),function(k,h,n,q,r,s,f,t,u,p){return s(r,{name:"columnLock",required:["body"],count:0,preload:function(){var c=this;c.grid.persist&&(c.count=c.grid.persist.registerAndLoad("columnLock",function(){return c.count}))},load:function(c,d){this.count=this.arg("count");var b=this,a=this.grid;t.body();
d.then(function(){if(!a.columnWidth||!a.columnWidth.arg("autoResize"))b.connect(a.body,"onAfterRow",function(a){b._lockColumns(a.node())}),b.connect(a.columnWidth,"onUpdate","_updateHeader"),b.connect(a.header,"onRender","_updateHeader"),b.connect(a.body,"onRender","_updateBody"),b.connect(a.body,"onAfterCell","_updateBody"),a.columnResizer&&(b.connect(a.columnResizer,"onResize","_updateHeader"),b.connect(a.columnResizer,"onResize","_updateBody")),b.connect(a,"_onResizeEnd","_updateHeader"),b.connect(a,
"_onResizeEnd","_updateBody"),b.connect(a.vScroller,"_onBodyChange","_updateBody"),b.connect(a,"resize","_updateUI"),a.header&&(a.header.loaded.then(function(){b._updateHeader()}),a.move&&a.move.column&&b.connect(a.move.column,"move","_updateHeader")),b._hackHScroller(),b.count&&b.lock(b.count);a.rowLock&&(b.connect(a.rowLock,"onLock",function(){b.grid.hScroller&&b.grid.hScroller._doScroll()}),b.connect(a.rowLock,"onUnlock",function(a){for(var c=b.grid.bodyNode.childNodes,d=0;d<a;d++)b._lockColumns(c[d])}));
b.loaded.callback()})},lock:function(c){if(!this.grid.columnWidth||!this.grid.columnWidth.arg("autoResize"))c>=this.grid._columns.length?console.warn("Warning: lock count is larger than columns count, do nothing."):(this.unlock(),c&&h.add(this.grid.domNode,"gridxColumnLock"),this.count=c,this._updateUI())},unlock:function(){if(!this.grid.columnWidth||!this.grid.columnWidth.arg("autoResize")){h.remove(this.grid.domNode,"gridxColumnLock");var c=u(".gridxHeaderRowInner",this.grid.headerNode)[0];this._unlockColumns(c);
f.forEach(this.grid.bodyNode.childNodes,this._unlockColumns,this);this.count=0;this._updateUI()}},_unlockColumns:function(c){for(var d=this.grid.isLeftToRight(),b=c.firstChild.rows[0],a=0;a<this.count;a++){var e=b.cells[a];h.remove(e,"gridxLockedCell");k.set(e,{height:"auto"})}c.style[d?"paddingLeft":"paddingRight"]="0px";c.style.width="auto";c.firstChild.style.height="auto"},_updateUI:function(){this.grid.header&&this._updateHeader();this._updateBody();this._updateScroller();this.grid.header.onRender();
this.grid.hScroller&&this.grid.hScroller._doScroll()},_lockColumns:function(c){if(this.count&&!(this.count>=this.grid._columns.length)){var d=h.contains(c,"gridxHeaderRowInner"),b=this.grid.isLeftToRight(),a=c.firstChild.rows[0],e;c.firstChild.style.height="auto";for(e=0;e<this.count;e++)k.set(a.cells[e],"height","auto");var f=n.getContentBox(a.cells[a.cells.length-1]).h;e=n.getMarginBox(a.cells[a.cells.length-1]).h;if(8<p("ie")||4<p("trident")){var g=k.getComputedStyle(c.firstChild).height;0<=String(g).toString().indexOf(".")&&
(e++,f++)}k.set(c.firstChild,"height",e+"px");g=d=d?this.grid.hLayout.lead:0;for(e=0;e<this.count;e++){var l=a.cells[e],m;h.add(l,"gridxLockedCell");m={height:f+"px"};m[b?"left":"right"]=g+"px";k.set(l,m);g+=l.offsetWidth}c.style[b?"paddingLeft":"paddingRight"]=g-d+"px";c.style.width=this.grid.bodyNode.offsetWidth-g+d+"px";c.scrollLeft=this.grid.hScroller?this.grid.hScroller.domNode.scrollLeft:0}},_updateHeader:function(){var c=this.grid.header.innerNode,d=c.scrollLeft;this._lockColumns(c);c.scrollLeft=
d;this._updateScroller()},_updateBody:function(){f.forEach(this.grid.bodyNode.childNodes,this._lockColumns,this)},_updateScroller:function(){this.grid.hScroller&&this.grid.hScroller.refresh()},_hackHScroller:function(){var c=this;q.mixin(this.grid.hScroller,{_doScroll:function(){var d=this.domNode.scrollLeft;c.count?f.forEach(this.grid.bodyNode.childNodes,function(b){b.scrollLeft=d;if("absolute"==b.style.position){var a=0;f.forEach(b.firstChild.rows[0].cells,function(b){h.contains(b,"gridxLockedCell")&&
(b.style.left=d+a+"px",a+=b.offsetWidth)})}}):this.grid.bodyNode.scrollLeft=d;this.grid.onHScroll(this.grid.hScroller._lastLeft)}})}})});
//# sourceMappingURL=ColumnLock.js.map