//>>built
define("gridx/modules/Dod","dojo/_base/kernel dojo/dom-construct dojo/dom-style dojo/dom-class dojo/dom-geometry dojo/_base/lang dojo/_base/Deferred dojo/_base/array ../core/_Module dojo/_base/declare dojo/_base/fx dojo/fx dojo/keys ../support/query dijit/a11y dijit/registry dojo/_base/event dojo/_base/sniff".split(" "),function(D,p,g,n,u,v,s,x,y,z,r,w,q,h,A,B,t,k){var C=function(){};return z(y,{name:"dod",required:["body"],useAnimation:!0,duration:750,defaultShow:!1,showExpando:!0,preload:function(){this.initFocus();
for(var a=this.grid,b=a._eventNames,c=b.length,d,f=0;f<c;f++)d="onDod"+b[f],a[d]=a[d]||C;this.connect(this.grid.body,"_onMouseEvent","_dodEventDispatcher")},load:function(a,b){var c=this,d=c.grid;c._rowMap={};c.connect(c.grid.body,"onAfterCell","_onAfterCell");c.connect(c.grid.body,"onAfterRow","_onAfterRow");c.connect(c.grid.bodyNode,"onclick","_onBodyClick");c.connect(c.grid.body,"onUnrender","_onBodyUnrender");c.connect(c.grid,"onCellKeyDown","_onCellKeyDown");c.connect(c.grid.body,"_onRowMouseOver",
"_onRowMouseOver");(k("ie")||k("trident"))&&c.aspect(c.grid.body,"renderRows",function(a,b,g){if(!("top"===g||"bottom"===g)){var h;for(g=a;g<a+b;g++)if(h=d.view.getRowInfo({visualIndex:g}),h=c._rowMap[h.rowId])h.dodLoaded=!1,h.dodLoadingNode=null,h.dodNode=null}},c,"before");c.grid.columnResizer&&c.connect(c.grid.columnResizer,"onResize","_onColumnResize");c.loaded.callback()},rowMixin:{showDetail:function(){this.grid.dod.show(this)},hideDetail:function(){this.grid.dod.hide(this)},toggleDetail:function(){this.grid.dod.toggle(this)},
refreshDetail:function(){this.grid.dod.refresh(this)},isDetailShown:function(){return this.grid.dod.isShown(this)}},show:function(a){var b=this._row(a),c=new s,d=this.grid;if(b.dodShown||b.inAnim)return c.errback("Row detail has already shown."),c;b.dodShown=!0;if(!a.node())return c.callback(a),c;var f=this._getExpando(a);f&&(f.firstChild.innerHTML="-");var f=a.node(),e=f.scrollWidth;b.dodLoadingNode||(b.dodLoadingNode=p.create("div",{className:"gridxDodLoadNode",innerHTML:this.grid.nls.loadingInfo}));
b.dodNode||(b.dodNode=p.create("div",{className:"gridxDodNode"}));p.place(b.dodLoadingNode,f,"last");p.place(b.dodNode,f,"last");g.set(b.dodLoadingNode,"width",e+"px");g.set(b.dodNode,"width",e+"px");g.set(b.dodNode,"visibility","hidden");g.set(b.dodNode,"overflow","hidden");g.set(b.dodNode,"height","0px");n.add(f,"gridxDodShown");if(b.dodLoaded)return this._detailLoadComplete(a,c),c;g.set(b.dodLoadingNode,"display","block");d.autoHeight&&d.vLayout.reLayout();b.inLoading=!0;this.grid.rowHeader&&(d=
h('[rowid\x3d"'+this.grid._escapeId(a.id)+'"].gridxRowHeaderRow',this.grid.rowHeader.bodyNode)[0],f=g.get(a.node(),"height"),g.set(d.firstChild,"height",f+"px"),g.set(d,"height",f+"px"));d=new s;this.arg("detailProvider")?this.detailProvider(this.grid,a.id,b.dodNode,d):d.callback();d.then(v.hitch(this,"_detailLoadComplete",a,c),v.hitch(this,"_detailLoadError",a,c));return c},hide:function(a){var b,c=this._row(a),d=this.grid,f=d._escapeId,e=new s,k=this;if(!c.dodShown||c.inAnim||c.inLoading)return e.errback("Row Detail has already been hidden."),
e;if(!a.node())return c.dodShown=!1,e.callback(a),e;n.remove(a.node(),"gridxDodShown");g.set(c.dodLoadingNode,"display","none");if(this.grid.rowHeader){b=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',this.grid.rowHeader.bodyNode)[0];var m=g.get(a.node(),"height");g.set(b.firstChild,"height",m+"px");g.set(b,"height",m+"px")}if(b=this._getExpando(a))b.firstChild.innerHTML="+";this.arg("useAnimation")?(c.inAnim=!0,w.wipeOut({node:c.dodNode,duration:this.arg("duration"),onEnd:function(){c.dodShown=!1;
c.inAnim=!1;c.defaultShow=!1;k.onHide(a);e.callback(a);d.body.onRender()}}).play(),this.grid.rowHeader&&(b=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',this.grid.rowHeader.bodyNode)[0],r.animateProperty({node:b.firstChild,duration:this.arg("duration"),properties:{height:{start:b.offsetHeight,end:b.offsetHeight-c.dodNode.scrollHeight,units:"px"}}}).play(),r.animateProperty({node:b,duration:this.arg("duration"),properties:{height:{start:b.offsetHeight,end:b.offsetHeight-c.dodNode.scrollHeight,units:"px"}}}).play())):
(c.dodShown=!1,c.inAnim=!1,this.grid.rowHeader&&(b=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',this.grid.rowHeader.bodyNode)[0],b.firstChild.style.height=b.offsetHeight-c.dodNode.scrollHeight+"px",b.style.height=b.offsetHeight-c.dodNode.scrollHeight+"px"),c.dodNode.style.display="none",d.body.onRender(),c.defaultShow=!1,this.onHide(a),e.callback(a));return e},toggle:function(a){this.isShown(a)?this.hide(a):this.show(a)},refresh:function(a){var b=this._row(a);b&&(b.dodShown&&!b.inAnim&&!b.inLoading)&&
(b.dodLoaded=!1,b.dodShown=!1,this.show(a))},isShown:function(a){return!!this._row(a).dodShown},onShow:function(a){},onHide:function(a){},initFocus:function(){this.grid.focus.registerArea({name:"navigabledod",priority:1,scope:this,doFocus:this._doFocus,doBlur:this._doBlur,onFocus:this._onFocus,onBlur:this._onBlur,connects:[this.connect(this.grid,"onCellKeyDown","_onCellKeyDown"),this.connect(this.grid,"onDodKeyDown","_onRowKeyDown")]})},_rowMap:null,_lastOpen:null,_row:function(a){var b=a;"object"===
typeof a&&(b=a.id);return this._rowMap[b]||(this._rowMap[b]={})},_onBodyClick:function(a){if(!(!n.contains(a.target,"gridxDodExpando")&&!n.contains(a.target,"gridxDodExpandoText")||this.grid.domNode!=h(a.target).closest(".gridx")[0])){for(a=a.target;a&&!n.contains(a,"gridxRow");)a=a.parentNode;a=a.getAttribute("rowindex");this.toggle(this.grid.row(parseInt(a,10)))}},_onRowMouseOver:function(a){var b=a.target,c=this._rowMap[a.rowId]?this._rowMap[a.rowId].dodNode:void 0;if(c){for(;b&&b!==c;)b=b.parentNode;
b&&(n.remove(c.parentNode,"gridxRowOver"),t.stop(a))}},_onAfterRow:function(a){var b=this._row(a);if(this.arg("showExpando")){var c=h("table",a.node())[0].rows[0].cells[0];p.create("span",{className:"gridxDodExpando",innerHTML:'\x3cspan class\x3d"gridxDodExpandoText"\x3e'+(this.arg("defaultShow")?"-":"+")+"\x3c/span\x3e"},c,"first")}if(this.isShown(a)||this.arg("defaultShow")&&void 0===b.dodShown)b.dodShown=!1,b.defaultShow=!0,this.show(a)},_onBodyUnrender:function(a){if(a&&(a=this._row(a))){var b=
a.dodNode;b&&b.parentNode&&b.parentNode.removeChild(b);(a=a.dodLoadingNode)&&a.parentNode&&a.parentNode.removeChild(a)}},_onAfterCell:function(a){this.arg("showExpando")&&0===a.node().cellIndex&&this._onAfterRow(a.row)},_onColumnResize:function(){h(".gridxDodNode",this.grid.bodyNode).forEach(function(a){g.set(a,"width",a.parentNode.firstChild.offsetWidth+"px")})},_detailLoadComplete:function(a,b){var c=this._row(a),d=this.grid,f=d._escapeId,e;if(this.isShown(a)){c.dodLoaded=!0;var k=h(".gridx",c.dodNode);
k.length&&(h.isGridInGrid[this.grid.id]=!0);if(c.defaultShow)c.dodNode.style.display="block",c.dodNode.style.visibility="visible",c.dodNode.style.height="auto",d.body.onRender(),this.grid.rowHeader&&(e=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',this.grid.rowHeader.bodyNode)[0],e.firstChild.style.height=a.node().firstChild.offsetHeight+c.dodNode.scrollHeight+"px",e.style.height=a.node().firstChild.offsetHeight+c.dodNode.scrollHeight+"px");else if("block"==g.get(c.dodLoadingNode,"display")&&(u.setMarginBox(c.dodNode,
{h:u.getMarginBox(c.dodLoadingNode).h}),g.set(c.dodNode,"display","block")),this.arg("useAnimation"))c.inAnim=!0,w.wipeIn({node:c.dodNode,duration:this.arg("duration"),onEnd:function(){c.inAnim=!1;d.body.onRender()}}).play(),this.grid.rowHeader&&(e=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',this.grid.rowHeader.bodyNode)[0],r.animateProperty({node:e.firstChild,duration:this.arg("duration"),onEnd:function(){try{var b=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',d.rowHeader.bodyNode)[0],e=a.node().firstChild.offsetHeight+
c.dodNode.offsetHeight;b.firstChild.style.height=e+"px"}catch(g){}},properties:{height:{start:e.offsetHeight,end:a.node().firstChild.offsetHeight+c.dodNode.scrollHeight,units:"px"}}}).play(),r.animateProperty({node:e,duration:this.arg("duration"),onEnd:function(){try{var b=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',d.rowHeader.bodyNode)[0],e=a.node().firstChild.offsetHeight+c.dodNode.offsetHeight;b.style.height=e+"px"}catch(g){}},properties:{height:{start:e.offsetHeight,end:a.node().firstChild.offsetHeight+
c.dodNode.scrollHeight,units:"px"}}}).play());else if(c.dodNode.style.display="block",c.dodNode.style.visibility="visible",c.dodNode.style.height="auto",d.body.onRender(),this.grid.rowHeader){e=h('[rowid\x3d"'+f(a.id)+'"].gridxRowHeaderRow',this.grid.rowHeader.bodyNode)[0];var m=a.node().firstChild.offsetHeight+c.dodNode.offsetHeight;e.firstChild.style.height=m+"px";e.style.height=m+"px"}g.set(c.dodLoadingNode,"display","none");c.inLoading=!1;e=this.grid._nestedGrids=this.grid._nestedGrids?this.grid._nestedGrids:
[];for(m=0;m<k.length;m++){var l=B.byNode(k[m]);l._outerGrid=d;e.push(l);l._refreshForDod||(l._refreshForDod=!0,this.connect(l.focus,"tab","_tab"),this.connect(l.lastFocusNode,"onfocus","_lastNodeFocus"),this.connect(l.domNode,"onfocus","_domNodeFocus"),this.connect(l.vLayout,"reLayout",function(){l._outerGrid&&l._outerGrid.vLayout.reLayout()}),this.connect(l,"onRowMouseOver",function(){l._outerGrid&&h(".gridxRowOver",l._outerGrid.bodyNode).removeClass("gridxRowOver")}))}d.vLayout.reLayout();this.onShow(a);
b.callback(a)}else b.errorback()},_detailLoadError:function(a){var b=this._row(a);b.dodLoaded=!1;this.isShown(a)&&(b.dodLoadingNode.innerHTML=this.grid.nls.loadFailInfo)},_showLoading:function(a){this._row(a).dodLoadingNode.innerHTML=this.grid.nls.loadingInfo},_getExpando:function(a){return!this.showExpando?null:(a=h("table",a.node())[0].rows[0].cells[0])?a.firstChild:null},_onCellKeyDown:function(a){var b=this.grid,c=b.focus,b=b.row(a.rowId,1);a.keyCode==q.DOWN_ARROW&&a.ctrlKey?(this.show(b),a.stopPropagation()):
a.keyCode==q.UP_ARROW&&a.ctrlKey&&(this.hide(b),a.stopPropagation());if(a.keyCode==q.F4&&!this._navigating&&"body"==c.currentArea()){if(this._beginNavigate(a.rowId,a.columnId)){c.focusArea("navigabledod");if(9>k("ie"))return a.returnValue=!1;t.stop(a)}}else a.keyCode==q.ESCAPE&&(this._navigating&&"navigabledod"==c.currentArea())&&(this._navigating=!1,c.focusArea("body"))},_onRowKeyDown:function(a){var b=this.grid.focus;a.keyCode==q.ESCAPE&&(this._navigating&&"navigabledod"==b.currentArea())&&(this._navigating=
!1,b.focusArea("body"))},_beginNavigate:function(a){var b=this.grid.row(a,1);if(!this._row(a).dodShown)return!1;this._navigating=!0;this._focusRowId=a;a=this._navElems=A._getTabNavigable(b.node());return(a.highest||a.last)&&(a.lowest||a.first)},_tab:function(a,b){this._step=a},_domNodeFocus:function(a){if(a&&-1===this._step){var b=this._navElems,c=b.lowest||b.first,b=b.highest||b.last||c;(k("ie")||k("trident")?a.srcElement:a.target)==c&&b.focus();return!1}},_lastNodeFocus:function(a){if(a&&1===this._step){var b=
this._navElems,c=b.lowest||b.first,b=b.highest||b.last||c;(k("ie")||k("trident")?a.srcElement:a.target)==b&&setTimeout(function(){c.focus()},1);return!1}},_doFocus:function(a,b){if(this._navigating){var c=this._navElems,d=function(){var a=0>b?c.highest||c.last:c.lowest||c.first;a&&a.focus()};k("webkit")?d():setTimeout(d,5);return!0}return!1},_onFocus:function(a){for(var b=a.target,c=this.grid.domNode;b&&b!==c&&!n.contains(b,"gridxDodNode");)b=b.parentNode;return b&&b!==c&&(c=b.parentNode)?(c=c.getAttribute("rowid"),
b!==a.target&&this._beginNavigate(c)):!1},_doBlur:function(a,b){if(a){var c=this._navElems,d=c.lowest||c.first,c=c.highest||c.last||d;(k("ie")||k("trident")?a.srcElement:a.target)==(0<b?c:d)&&t.stop(a);return!1}this._navigating=!1;return!0},_onBlur:function(a){this._navigating=!1},_dodEventDispatcher:function(a,b){var c=b.target,d="onDod"+a,f=this.grid;x.forEach("rowId columnId rowIndex visualIndex columnIndex parentId cellNode".split(" "),function(a){a in b&&(b[a]=void 0)});for(;c&&!n.contains(c,
"gridxDodNode");)c=c.parentNode;if(c&&(c=c.parentNode,b.rowId=c.getAttribute("rowid"),b.parentId=c.getAttribute("parentid"),b.rowIndex=parseInt(c.getAttribute("rowindex"),10),b.visualIndex=parseInt(c.getAttribute("visualindex"),10),f[d]))f[d](b)},endFunc:function(){}})});
//# sourceMappingURL=Dod.js.map