//>>built
define("gridx/modules/Edit","dojo/_base/declare dojo/_base/lang dojo/query dojo/_base/json dojo/_base/Deferred dojo/_base/sniff dojo/_base/array dojo/DeferredList dojo/dom-class dojo/dom-style dojo/dom-geometry dojo/dom-construct dojo/keys dojox/gesture/tap dijit/a11y ../core/_Module dojo/date/locale ../core/model/extensions/Modify dojo/_base/event dijit/form/Button dijit/Toolbar dijit/form/TextBox".split(" "),function(w,l,k,x,p,F,y,G,n,z,r,s,t,A,B,C,q,D,H){function u(a,b,d,c){return a.storePattern&&
("date"==a.dataType||"time"==a.dataType)?q.parse(b,a.storePattern):void 0===d?null:d}function E(a,b,d,c){return(b=q.parse(c[a],b))?q.format(b,d):c[a]}function v(a){return a&&function(b,d,c){var f=c.gridCellEditField;c=c.cell;var e=c.column.editorArgs;f.set(e&&e.valueField||"value",a(d,b,c,f))}}return w(C,{name:"edit",forced:["cellWidget"],modelExtensions:[D],constructor:function(){this._init()},getAPIPath:function(){return{edit:this}},preload:function(){var a=this,b=a.grid;if(a.arg("lazySave")){var d=
function(a){var b=a.node(),d=k(".gridxCellBg",b),g=a.row.id,h=a.column.id;a.row.visualIndex();if(!d.length){var m=z.getComputedStyle(b),m=parseInt(r.getPadBorderExtents(b,m).l,10),d=["\x3cdiv class\x3d'gridxCellEditedBgWrapper'\x3e","\x3cdiv\trowid\x3d'"+g+"' ","colid\x3d'"+h+"' ","class\x3d'gridxCellEditedBg'\x3e\x3cspan\x3e\u25e5\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e"].join(""),g=s.toDom(d),d=g.firstChild;s.place(g,a.node(),"first");a=r.position(d);b=r.position(b);g.style.top=b.y-a.y+"px";g.style.left=
m+"px"}};a.connect(b.body,"onAfterRow",function(c){var f=b._columnsById;k(".gridxCell",c.node()).forEach(function(e){e=e.getAttribute("colid");a.model.isChanged(c.id,f[e].field)?(b.body.addClass(c.id,e,"gridxCellChanged"),d(b.cell(c.id,e,1))):b.body.removeClass(c.id,e,"gridxCellChanged")})});a.connect(b.body,"onAfterCell",function(c){c.node();var f=c.row.id,e=c.column.id;c.row.visualIndex();a.model.isChanged(f,b._columnsById[e].field)?(b.body.addClass(f,e,"gridxCellChanged"),d(c)):(b.body.removeClass(f,
e,"gridxCellChanged"),c=c.node(),c=k(".gridxCellBg",c),c.length&&s.destroy(c))})}b.domNode.removeAttribute("aria-readonly");b.touch?(a.connect(b.bodyNode,A.doubletap,function(c){c=k(c.target).closest(".gridxCell",b.bodyNode);var d=c.closest(".gridxRow",b.bodyNode)[0];c=c[0];d&&c&&a._onUIBegin({rowId:d.getAttribute("rowid"),columnId:c.getAttribute("colid")})}),a.aspect(b,"onCellTouchEnd",function(c){var d=b._columnsById[c.columnId];k(".gridxEditFocus",b.bodyNode).removeClass("gridxEditFocus");d.alwaysEditing&&
a._showButtons(c.rowId,c.columnId)})):a.aspect(b,"onCellDblClick",function(b){!n.contains(b.target,"gridxTreeExpandoIcon")&&!n.contains(b.target,"gridxTreeExpandoInner")&&a._onUIBegin(b)});a.aspect(b.cellWidget,"onCellWidgetCreated","_onCellWidgetCreated");a.aspect(b.cellWidget,"initializeCellWidget",function(a,b){var d=b.column;d.initializeEditor&&a.gridCellEditField&&d.initializeEditor(a.gridCellEditField,b)});a.aspect(b.cellWidget,"uninitializeCellWidget",function(a,b){var d=b.column;d.uninitializeEditor&&
a.gridCellEditField&&d.uninitializeEditor(a.gridCellEditField,b)});a.aspect(b.cellWidget,"collectCellWidgetConnects",function(a,b){var d=a.cell.column;d.getEditorConnects&&(d=d.getEditorConnects(a,a.cell),b.push.apply(b,d))});a.aspect(b.body,"onAfterRow",function(a){k(".gridxCell",a.node()).forEach(function(a){b._columnsById[a.getAttribute("colid")].editable&&a.removeAttribute("aria-readonly")})})},lazySave:!1,load:function(){this._initFocus();this.loaded.callback()},cellMixin:{beginEdit:function(){return this.grid.edit.begin(this.row.id,
this.column.id)},cancelEdit:function(){return this.grid.edit.cancel(this.row.id,this.column.id)},applyEdit:function(){return this.grid.edit.apply(this.row.id,this.column.id)},isEditing:function(){return this.grid.edit.isEditing(this.row.id,this.column.id)},editor:function(){return this.grid.edit.getEditor(this.row.id,this.column.id)},isEditable:function(){var a=this.column;return a.isEditable()&&(!a.canEdit||a.canEdit(this))}},columnMixin:{isEditable:function(){return this.grid._columnsById[this.id].editable},
isAlwaysEditing:function(){return this.grid._columnsById[this.id].alwaysEditing},setEditable:function(a){this.grid._columnsById[this.id].editable=!!a;return this},editor:function(){return this.grid._columnsById[this.id].editor},setEditor:function(a,b){this.grid.edit.setEditor(this.id,a,b);return this}},begin:function(a,b){var d=new p,c=this,f=c.grid;if(c.isEditing(a,b))c._record(a,b),c._focusEditor(a,b),d.callback(!0),c.onBegin(f.cell(a,b,1));else{var e=f.row(a,1),g=f._columnsById[b];e&&e.cell(b,
1).isEditable()?(f.cellWidget.setCellDecorator(a,b,c._getDecorator(b),v(g.editorArgs&&g.editorArgs.toEditor||l.partial(u,g))),c._record(a,b),f.body.refreshCell(e.visualIndex(),g.index).then(function(){f.resize();c._focusEditor(a,b);d.callback(!0);c.onBegin(f.cell(a,b,1))})):d.callback(!1)}return d},cancel:function(a,b){var d=new p,c=this,f=c.grid,e=c.model,g=f.row(a,1);if(g){var h=f.cellWidget,m=f._columnsById[b];m&&(m.alwaysEditing?(e=e.byId(a),h=h.getCellWidget(a,b),h.setValue(e.data[b],e.rawData[m.field]),
d.callback(),c.onCancel(f.cell(a,b,1))):(c._erase(a,b),h.restoreCellDecorator(a,b),f.body.refreshCell(g.visualIndex(),m.index).then(function(){d.callback();var e=f.cell(a,b,1),g=e&&e.node();g&&(g.removeAttribute("aria-labelledby"),(!g.innerHTML||"\x26nbsp;"===g.innerHTML)&&g.setAttribute("aria-label","empty cell"));c.onCancel(e)})))}else d.callback();return d},apply:function(a,b){var d=new p,c=this,f=c.grid,e=f.cell(a,b,1);if(e){var g=f.cellWidget.getCellWidget(a,b),h=g&&g.gridCellEditField;if(h&&
(!l.isFunction(h.isValid)||h.isValid())){var m=e.column.editorArgs,h=h.get(m&&m.valueField||"value"),k=function(g,h){g||console.warn("Can not apply change! Error message: ",h);c._erase(a,b);e.column.alwaysEditing?(d.callback(g),c.onApply(e,g,h,c.arg("lazy"))):(f.cellWidget.restoreCellDecorator(a,b),f.body.refreshCell(e.row.visualIndex(),e.column.index()).then(function(){d.callback(g);f.resize();var a=e.node();a.removeAttribute("aria-labelledby");(!a.innerHTML||"\x26nbsp;"===a.innerHTML)&&a.setAttribute("aria-label",
"empty cell");c.onApply(e,g,h,c.arg("lazy"))}))};try{h=isNaN(h)&&"number"===typeof h?"":h,m&&m.fromEditor?h=m.fromEditor(h,g.cell):e.column.storePattern&&(h=q.format(h,e.column.storePattern)),l.isFunction(e.column.customApplyEdit)?p.when(e.column.customApplyEdit(e,h),function(){k(!0)},function(a){k(!1,a)}):e.rawData()===h?k(!0):c.arg("lazySave")?(g={},g[f._columnsById[b].field]=h,c.model.set(a,g),k(!0)):p.when(e.setRawData(h),function(){k(!0)},function(a){k(!1,a)})}catch(n){k(!1,n)}return d}}d.callback(!1);
return d},isEditing:function(a,b){var d=this.grid._columnsById[b];return d&&d.alwaysEditing?!0:!!this.getEditor(a,b)},setEditor:function(a,b,d){a=this.grid._columnsById[a];var c=a.editorArgs=a.editorArgs||{};a.editor=b;l.mixin(c,d||{})},getEditor:function(a,b){var d=this.grid.cellWidget.getCellWidget(a,b);return d&&d.gridCellEditField},getLazyData:function(a,b){var d,c=this.grid._columnsById[b].field;if(this.arg("lazy")&&(d=this._lazyDataChangeList[a]))return d[c]?d[c].list[d[c].index]:void 0},onBegin:function(){},
onApply:function(){},onCancel:function(){},_init:function(){this._editingCells={};this._lazyIds={};this._lazyData={};this._lazyDataChangeList={};this._inCallBackMode=!1;this.grid.touch&&(this.buttons=1);for(var a=0,b=this.grid._columns,d=b.length;a<d;++a){var c=b[a];if(c.storePattern&&c.field&&("date"==c.dataType||"time"==c.dataType)){c.gridPattern=c.gridPattern||!l.isFunction(c.formatter)&&(l.isObject(c.formatter)||"string"==typeof c.formatter)&&c.formatter||c.storePattern;var f;l.isString(c.storePattern)&&
(f=c.storePattern,c.storePattern={},c.storePattern[c.dataType+"Pattern"]=f);c.storePattern.selector=c.dataType;l.isString(c.gridPattern)&&(f=c.gridPattern,c.gridPattern={},c.gridPattern[c.dataType+"Pattern"]=f);c.gridPattern.selector=c.dataType;c.formatter=l.partial(E,c.field,c.storePattern,c.gridPattern)}}this._initAlwaysEdit()},_initAlwaysEdit:function(){var a=this;y.forEach(a.grid._columns,function(b){if(b.alwaysEditing){b.editable=!0;b.navigable=!0;var d=b.needCellWidget;b.needCellWidget=function(a){return(!d||
d.apply(b,arguments))&&a.isEditable()};b.decorator!=a._dummyDecorator&&(b._userDec=b.decorator);b.userDecorator=a._getDecorator(b.id);b.setCellValue=v(b.editorArgs&&b.editorArgs.toEditor||l.partial(u,b));b.decorator=a._dummyDecorator;b._cellWidgets={};b._backupWidgets=[]}})},_dummyDecorator:function(a,b,d,c){var f=c.column;return!f.needCellWidget||f.needCellWidget(c)?"":f._userDec?f._userDec(a,b,d,c):a},_getColumnEditor:function(a){a=this.grid._columnsById[a].editor;return l.isFunction(a)?a.prototype.declaredClass:
l.isString(a)?a:"dijit.form.TextBox"},_onCellWidgetCreated:function(a,b){var d=this,c=a.gridCellEditField;if(c){if(a.btns){var f=function(b){b.stopPropagation();a.cell.applyEdit().then(function(b){b&&(n.remove(a.btns,"gridxEditFocus"),d.grid.body.onRender(),d._blur())})},e=function(b){b.stopPropagation();a.cell.cancelEdit().then(function(){n.remove(a.btns,"gridxEditFocus");d.grid.body.onRender();d._blur()})};a.connect(a.btnOK,"onclick",f);a.connect(a.btnOK,"ontouchend",f);a.connect(a.btnCancel,"onclick",
e);a.connect(a.btnCancel,"ontouchend",e)}else b.alwaysEditing&&a.connect(c,"onChange",function(){var f=a.cell.row.id,e=b.editorArgs&&b.editorArgs.applyDelay||500;clearTimeout(c._timeoutApply);c._timeoutApply=setTimeout(function(){d.apply(f,b.id)},e)});if(b.onEditorCreated)b.onEditorCreated(c,b)}},_focusEditor:function(a,b,d){if((a=this.getEditor(a,b))&&!a.focused&&l.isFunction(a.focus)||d)this.grid.hScroller.scrollToColumn(b),a.focus()},_showButtons:function(a,b){var d=this.grid;if(d._columnsById[b].alwaysEditing){k(".gridxEditFocus",
d.bodyNode).removeClass("gridxEditFocus");var c=d.cellWidget.getCellWidget(a,b);c&&c.btns&&n.add(c.btns,"gridxEditFocus");d.body.onRender()}},_hideButtons:function(){k(".gridxEditFocus",this.grid.bodyNode).removeClass("gridxEditFocus");this.grid.body.onRender()},_getDecorator:function(a){var b=this._getColumnEditor(a),d=this.grid._columnsById[a];a=d.editorArgs||{};var c=a.useGridData,f=a.constraints||{},e=a.props||"";a=d.gridPattern||d.storePattern;var g=d.textDir||this.grid.textDir;a&&(f=l.mixin({},
a,f));f=x.toJson(f);f=f.substring(1,f.length-1);e=e?e+",scrollOnFocus: false":"scrollOnFocus: false";g?e+=[e?", ":"",'dir: "',this.grid.isLeftToRight()?"ltr":"rtl",'", textDir: "',g,f?'", ':'"'].join(""):e&&f&&(e+=", ");var h=this;return function(){return[h.arg("buttons")?["\x3cdiv class\x3d'gridxEditButtons ",d.alwaysEditing?"gridxAlwaysEdit":"","' data-dojo-attach-point\x3d'btns'\x3e\x3cdiv tabindex\x3d'0' class\x3d'gridxEditOK' data-dojo-attach-point\x3d'btnOK'\x3e\x3c/div\x3e\x3cdiv tabindex\x3d'0' class\x3d'gridxEditCancel' data-dojo-attach-point\x3d'btnCancel'\x3e\x3c/div\x3e\x3c/div\x3e"].join(""):
"","\x3cdiv data-dojo-type\x3d'",b,"' data-dojo-attach-point\x3d'gridCellEditField' class\x3d'gridxCellEditor gridxHasGridCellValue ",c?"":"gridxUseStoreData","' data-dojo-props\x3d'",e,f,"'\x3e\x3c/div\x3e"].join("")}},_record:function(a,b){var d=this._editingCells,c=d[a];c||(c=d[a]={});c[b]=1},_erase:function(a,b){var d=this._editingCells[a];d&&delete d[b]},_applyAll:function(){var a=this._editingCells,b,d;for(b in a)for(d in a[b])this.apply(b,d)},_onUIBegin:function(a){this.isEditing(a.rowId,a.columnId)||
this._applyAll();return this.begin(a.rowId,a.columnId)},_initFocus:function(){var a=this,b=a.grid,d=b.focus;d?d.registerArea({name:"edit",priority:1,scope:a,doFocus:a._onFocus,doBlur:a._doBlur,onFocus:a._onFocus,onBlur:a._onBlur,connects:[a.aspect(b,"onCellKeyDown","_onKey"),a.aspect(a,"_focusEditor","_focus"),a.aspect(b.focus,"onFocusArea",function(c){"navigablecell"==c&&a._showButtons(b.navigableCell._focusRowId,b.navigableCell._focusColId)}),a.aspect(b.focus,"onBlurArea",function(b){"navigablecell"==
b&&a._hideButtons()})]}):a.aspect(b,"onCellMouseDown",function(b){var d=a._editingCells;(!d[b.rowId]||!d[b.rowId][b.columnId])&&a._applyAll()})},_onFocus:function(a){if(a){var b=k(a.target).closest(".gridxCell",this.grid.bodyNode)[0];return b&&(a=b.getAttribute("colid"),b=b.parentNode.parentNode.parentNode.parentNode.getAttribute("rowid"),this.isEditing(b,a))?(this._record(b,a),!this.grid._columnsById[a].alwaysEditing):!1}return this._editing},_doBlur:function(a,b){var d=this,c=d.grid,f=c.view,e=
c.body;if(d._editing&&b){var g=c.body.getCellNode({rowId:d._focusCellRow,colId:d._focusCellCol}),g=B._getTabNavigable(g);if(a&&(!g.first&&!g.last||a.target==(0>b?g.first:g.last)))c.focus.stopEvent(a),g=f.getRowInfo({parentId:d.model.parentId(d._focusCellRow),rowIndex:d.model.idToIndex(d._focusCellRow)}).visualIndex,e._nextCell(g,c._columnsById[d._focusCellCol].index,0<b?1:-1,function(a,b){return c._columns[b].editable}).then(function(a){d._applyAll();d._focusCellCol=c._columns[a.c].id;var b=f.getRowInfo({visualIndex:a.r});
d._focusCellRow=d.model.indexToId(b.rowIndex,b.parentId);e._focusCellCol=a.c;e._focusCellRow=a.r;d.begin(d._focusCellRow,d._focusCellCol)});return!1}return!0},_onBlur:function(){this._applyAll();this._editing=!1;return!0},_focus:function(a,b){this._editing=!0;this._focusCellCol=b;this._focusCellRow=a;this.grid.focus.focusArea("edit")},_blur:function(){this._editing=!1;var a=this.grid.focus;a&&a.focusArea("body")},_onKey:function(a){var b=this,d=b.grid,c=d._isCtrlKey(a),f=d._columnsById[a.columnId];
if(f.editable){var e=b.isEditing(a.rowId,a.columnId);a.keyCode==t.ENTER&&!f.editorIgnoresEnter?e?b.apply(a.rowId,a.columnId).then(function(c){f.alwaysEditing?(b._focusEditor(a.rowId,a.columnId),b._showButtons(a.rowId,a.columnId)):c&&b._blur()}):"body"==d.focus.currentArea()&&(d.focus.stopEvent(a),b._onUIBegin(a)):a.keyCode==t.ESCAPE&&e?(d.focus.stopEvent(a),b.cancel(a.rowId,a.columnId).then(l.hitch(b,b._blur)).then(function(){b._hideButtons();d.focus.focusArea("body")})):90==a.keyCode&&c?b.arg("lazySave")&&
b.model.undo():89==a.keyCode&&c?b.arg("lazySave")&&b.model.redo():83==a.keyCode&&c&&b.arg("lazySave")&&(b.model.save(),a.preventDefault())}}})});
//# sourceMappingURL=Edit.js.map