//>>built
define("gridx/modules/ExpandableColumn","dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/event dojo/keys dojo/aspect dojo/query dojo/string dojo/dom-class dojo/dom-construct ../core/_Module ./HiddenColumns".split(" "),function(m,g,q,n,r,s,h,t,e,l,u,p,v,w){return m(p,{name:"expandedColumn",_parentCols:null,required:["header"],preload:function(){this.inherited(arguments)},load:function(a,c){var b=this,d=b.grid;b._cols=d._columns.slice();b._parentCols={};var k=[];g.forEach(b._cols,function(f){if(f.expanded)k.push(f.id);
else if(f.parentColumn){b._parentCols[f.parentColumn]=1;var a=this._colById(f.parentColumn);a.expanded||(k.push(f.id),a.expanded=!1)}},this);this.expandoBar=l.create("div",{className:"gridxColumnExpandoBar"});this.connect(d.columnWidth,"onUpdate","_updateUI");this.grid.vLayout.register(this,"expandoBar","headerNode",1);this.connect(d,"onHeaderCellMouseOver",function(a){e.add(this._expandoCellByColumnId(a.columnId),"gridxColumnExpandoHighlight")},this);this.connect(d,"onHeaderCellMouseOut",function(a){e.remove(this._expandoCellByColumnId(a.columnId),
"gridxColumnExpandoHighlight")},this);this.connect(this.expandoBar,"onmouseover",function(a){var b=null;/td/i.test(a.target.tagName)?b=a.target:e.contains(a.target,"gridxColumnExpando")&&(b=a.target.parentNode);b&&(a=b.getAttribute("data-column-id"),e.add(b,"gridxColumnExpandoHighlight"),e.add(this._headerCellByColumnId(a),"gridxCellHighlight"))},this);this.connect(this.expandoBar,"onmouseout",function(a){var b=null;/td/i.test(a.target.tagName)?b=a.target:e.contains(a.target,"gridxColumnExpando")&&
(b=a.target.parentNode);b&&(a=b.getAttribute("data-column-id"),e.remove(b,"gridxColumnExpandoHighlight"),e.remove(this._headerCellByColumnId(a),"gridxCellHighlight"))},this);this.connect(this.expandBar,"onclick",function(a){e.contains(a.target,"gridxColumnExpando")&&(a=a.target.parentNode.getAttribute("data-column-id"),this.expand(a))},this);this.connect(this.grid.header.innerNode,"onkeyup",function(a){var b;77==a.keyCode&&a.ctrlKey&&(b=a.target,e.contains(b,"gridxGroupHeader")?(b=b.getAttribute("groupid").split("-").pop(),
b=this._colById(b).parentColumn,this.collapse(b),this._focusById(b)):e.contains(b,"gridxCell")&&(b=b.getAttribute("colid"),this._parentCols[b]&&(this.expand(b),this._focusById(b))),n.stop(a))},this);this.connect(this.grid.header,"refresh",function(){d.header.hidden?(d.header.domNode.parentNode.style.overflow="hidden",this.expandoBar.style.display="none"):(d.header.domNode.parentNode.style.overflow="visible",this.expandoBar.style.display="block")});this.connect(this.grid,"onHScroll",function(a){this.expandoBar.scrollLeft=
a},this);k.length?c.then(function(){b.add.apply(b,k);b._refreshHeader();b.loaded.callback()}):b.loaded.callback();b.aspect(d,"setColumns","_onSetColumns")},_onSetColumns:function(){var a=this,c=a.grid;a._cols=c._columns.slice();a._parentCols={};var b=[];g.forEach(a._cols,function(c){if(c.expanded)b.push(c.id);else if(c.parentColumn){a._parentCols[c.parentColumn]=1;var e=this._colById(c.parentColumn);e.expanded||(b.push(c.id),e.expanded=!1)}},this);c.header._build();c.body.refresh();b.length&&(a.add.apply(a,
b),a._refreshHeader())},expand:function(a){var c=g.filter(this._cols,function(b){return b.parentColumn==a});this.add(a);this.remove.apply(this,c);this._colById(a).expanded=!0;this._refreshHeader()},collapse:function(a){var c=g.filter(this._cols,function(b){return b.parentColumn==a});this.remove(a);this.add.apply(this,c);this._colById(a).expanded=!1;this._refreshHeader()},_updateUI:function(){var a=['\x3ctable role\x3d"presentation" border\x3d"0" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\x3ctr\x3e'];
g.forEach(this.grid._columns,function(c){a.push('\x3ctd data-column-id\x3d"',c.id,'" aria-readonly\x3d"true" tabindex\x3d"-1" class\x3d"gridxColumnExpandoCell"\x3e');this._parentCols[c.id]&&a.push('\x3cspan class\x3d"gridxColumnExpando"\x3e\x3c/span\x3e');a.push("\x3c/td\x3e")},this);a.push("\x3c/tr\x3e\x3c/table\x3e");this.expandoBar.innerHTML=a.join("");this.grid._columns.length&&(this.expandoBar.style.marginRight=this.grid.header.innerNode.style.marginRight,this.expandoBar.style.marginLeft=this.grid.header.innerNode.style.marginLeft,
h("table",this.grid.headerNode),g.forEach(this.expandoBar.firstChild.rows[0].cells,function(a,b){var d=a.getAttribute("data-column-id");if(d=this.grid._columnsById[d])a.style.width=d.width,a.style.minWidth=d.width,a.style.maxWidth=d.width},this))},_createExpandNode:function(a,c){var b=l.create("div",{innerHTML:"",className:"gridxColumnExpandNode"});if(this._parentCols[c.id]){b.innerHTML='\x3cspan class\x3d"gridxColumnExpandNodeIcon"\x3e\x3c/span\x3e';var d=this;b.onclick=function(){d.expand(c.id)}}else b.innerHTML=
"";return b},_headerCellByColumnId:function(a){var c=h('td[colid\x3d"'+a+'"]',this.grid.headerNode)[0];c||(c=h('td[data-map-column-id\x3d"'+a+'"]',this.grid.headerNode)[0]);return c},_expandoCellByColumnId:function(a){return h('td[data-column-id\x3d"'+a+'"]',this.expandoBar)[0]},_refreshHeader:function(){for(var a=[],c=this.grid._columns,b=null,d=0,e=0;e<c.length;e++){var f=c[e];if(f.parentColumn){0<d&&(a.push(d),d=0);if(!b||b._colId!=f.parentColumn)b&&b._colId!=f.parentColumn&&a.push(b),b={_colId:f.parentColumn,
name:this._colById(f.parentColumn).name,children:0};b.children++}else b&&a.push(b),d++,b=null}delete this.grid.header.groups;this.grid.headerGroups=a;this.grid.header.refresh();var g=this;h(".gridxGroupHeader",this.grid.headerNode).forEach(function(a){var b=a.getAttribute("groupid").split("-").pop(),b=g._colById(b).parentColumn;a.setAttribute("data-map-column-id",b);var c=l.create("div",{innerHTML:'\x3cspan class\x3d"gridxColumnCollapseNodeIcon"\x3e\x3c/span\x3e',className:"gridxColumnCollapseNode"});
c.onclick=function(){g.collapse(b)};a.firstChild.insertBefore(c,a.firstChild.firstChild)})},_colById:function(a){return this.grid._columnsById[a]||g.filter(this._cols,function(c){return c.id==a})[0]},_focusById:function(a){(a=this._headerCellByColumnId(a))&&this.grid.header._focusNode(a)}})});
//# sourceMappingURL=ExpandableColumn.js.map