//>>built
define("gridx/modules/Layer","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/sniff dojo/dom-class dojo/dom-geometry dojo/query dojo/keys ../core/_Module".split(" "),function(u,v,w,r,k,p,m,y,x){function s(c,d){for(;c.childNodes.length;)d.appendChild(c.firstChild)}u.experimental("gridx/modules/Layer");var t="__nextLevelButton__";return v(x,{name:"layer",buttonColumnWidth:"20px",constructor:function(){function c(a){var b=a.getAttribute("colid"),b=e.header.getHeaderNode(b);a.style.width=
b.style.width;a.style.minWidth=b.style.minWidth;a.style.maxWidth=b.style.maxWidth}function d(b){b.columnId==t&&b.cellNode.childNodes.length&&(e.focus.focusArea("header"),setTimeout(function(){a.down(b.rowId)},0))}var a=this,e=a.grid,b=a._tmpBodyNode=document.createElement("div"),f=a._contextNode=document.createElement("div"),g=a._wrapper1=document.createElement("div"),h=a._wrapper2=document.createElement("div");b.setAttribute("class","gridxBody");f.setAttribute("class","gridxLayerContext");f.style.overflow=
"hidden";f.setAttribute("id","testContextNode");g.setAttribute("class","gridxLayerWrapper");h.setAttribute("class","gridxLayerWrapper");a._parentStack=[];a.connect(f,"onmousedown","up");a.aspect(e.columnWidth,"onUpdate",function(){m(".gridxCell",g).forEach(c);m(".gridxCell",h).forEach(c);f.firstChild&&(f.style.height=f.firstChild.offsetHeight+"px");var a=parseInt(e.header.innerNode.style.marginRight),b=parseInt(e.header.innerNode.style.marginLeft);f.style.marginRight=a?a+1+"px":a+0+"px";f.style.marginLeft=
b?b+1+"px":b+0+"px"});b=a.arg("buttonColumnWidth");a._col=w.mixin({id:t,headerStyle:"text-align:center;",style:function(a){return"text-align:center;"+(a.model.hasChildren(a.row.id)?"cursor:pointer;":"")},rowSelectable:!1,sortable:!1,filterable:!1,editable:!1,padding:!1,ignore:!0,declaredWidth:b,width:b,decorator:function(b,c){return a.model.hasChildren(c)?'\x3cdiv class\x3d"gridxLayerHasChildren"\x3e\x3c/div\x3e':""}},a.arg("buttonColumnArgs")||{});a._onSetColumns();a.aspect(e,"setColumns","_onSetColumns");
a.aspect(e,"setStore",function(){a._parentStack=[];g.innerHTML=h.innerHTML="";f.firstChild&&(f.removeChild(f.firstChild),f.style.height=0,e.vLayout.reLayout())});e.touch&&a.aspect(e,"onCellTouchStart",d);a.aspect(e,"onCellMouseDown",d)},preload:function(){this.grid.vLayout.register(this,"_contextNode","headerNode",10);this.aspect(this.grid,"onHScroll","_onHScroll")},_onHScroll:function(c){var d=this.grid;if(this._contextNode){var a=this._contextNode;if((r("webkit")||8>r("ie"))&&!d.isLeftToRight())c=
a.scrollWidth-a.offsetWidth-c;a.scrollLeft=this._scrollLeft=c}},onReady:function(){},onFinish:function(){},down:function(c){var d=this.model;if(!this._lock&&d.hasChildren(c)&&String(d.parentId(c))===String(d.layerId())){this._lock=1;var a=this.grid,e=a.bodyNode,b=e.offsetWidth,f=this._tmpBodyNode,g=this._wrapper1,h=this._wrapper2,l=a.body.getRowNode({rowId:c}),n=p.position(l),m=p.position(this._contextNode),q=l.cloneNode(!0);k.add(l,"gridxLayerLoading");h.appendChild(q);this._parentStack.push(q);
q._pos=a.vScroller.position();this._bodyScrollTop=e.scrollTop;s(e,f);e.style.left=b+"px";e.style.zIndex=1;f.style.left=0;f.style.zIndex=0;h.style.top=n.y-m.y+"px";h.style.zIndex=-1;a.vScrollerNode.style.zIndex=9999;d.setLayer(c);this._refresh(function(){k.remove(l,"gridxLayerLoading");h.style.zIndex=9999;a.vScroller.scroll(0);k.add(g,"gridxLayerHSlide");k.add(h,"gridxLayerVSlide");e.style.left=0;f.style.left=-b+"px";g.style.left=-b+"px";h.style.top=0},{isDown:!0,rowId:c,parentRowNode:q})}},up:function(){var c=
this,d=c.model;if(!c._lock&&d.isId(d.layerId())){c._lock=1;var a=c.grid,e=a.bodyNode,b=c._tmpBodyNode,f=e.offsetWidth,g=c._wrapper1,h=c._wrapper2,l=c._parentStack[c._parentStack.length-2],n=c._parentStack.pop(),m=n.getAttribute("rowid");l&&h.appendChild(l);c._bodyScrollTop=e.scrollTop;s(e,b);e.style.left=-f+"px";e.style.zIndex=0;b.style.left=0;b.style.zIndex=1;g.style.top=0;g.style.zIndex=2;h.style.left=-f+"px";a.vScrollerNode.style.zIndex=9999;d.layerUp();c._refresh(function(){var d,l;n&&(a.vScroller.scroll(n._pos),
d=p.position(a.body.getRowNode({rowId:m})),l=p.position(c._contextNode));k.add(g,"gridxLayerVSlide");k.add(h,"gridxLayerHSlide");e.style.left=0;b.style.left=f+"px";n&&(g.style.top=d.y-l.y+"px");h.style.left=0},{parentRowNode:n})}},_onSetColumns:function(){var c=this.grid,d=this._col;d.index=c._columns.length;c._columns.push(d);c._columnsById[d.id]=d},_onTransitionEnd:function(){var c=this.model,d=this.grid,a=d.mainNode,e=d.bodyNode,b=this._tmpBodyNode,f=this._contextNode,g=this._wrapper1,h=this._wrapper2;
if(this._lock){a.removeChild(b);a.removeChild(g);f.appendChild(h);f.style.height=h.offsetHeight+"px";k.remove(b,"gridxSlideRefresh");k.remove(e,"gridxSlideRefresh");k.remove(g,"gridxLayerHSlide gridxLayerVSlide");k.remove(h,"gridxLayerHSlide gridxLayerVSlide");g.childNodes.length&&g.removeChild(g.firstChild);a=this._wrapper1;this._wrapper1=this._wrapper2;this._wrapper2=a;g.style.left=0;g.style.zIndex="";g.style.top=0;h.style.left=0;h.style.zIndex="";h.style.top=0;e.style.paddingTop=0;e.style.zIndex=
"";b.style.paddingTop=0;b.style.zIndex="";d.vScrollerNode.style.zIndex="";d.vLayout.reLayout();for(e=0;e<b.childNodes.length;++e)if(g=b.childNodes[e].getAttribute("rowid"),c.isId(g))d.body.onUnrender(g);b.innerHTML="";this._lock=d.body._skipUnrender=0}},_refresh:function(c,d){var a=this,e,b=a.grid,f=b.bodyNode,g=a._tmpBodyNode,h=document.createDocumentFragment();h.appendChild(g);h.appendChild(a._wrapper1);h.appendChild(a._wrapper2);b.mainNode.appendChild(h);g.scrollTop=a._bodyScrollTop;g.style.paddingTop=
a._wrapper1.offsetHeight+"px";f.style.paddingTop=a._wrapper2.offsetHeight+"px";a._contextNode.style.height=0;a._paging=b.view.paging;b.view.paging=0;b.vLayout.reLayout();d.isDown?m(".gridxLayerHasChildren",d.parentRowNode).removeClass("gridxLayerHasChildren").addClass("gridxLayerLevelUp"):d.parentRowNode&&m(".gridxLayerLevelUp",d.parentRowNode).removeClass("gridxLayerLevelUp").addClass("gridxLayerHasChildren");a.onReady(d);b.body._skipUnrender=1;d.isDown&&(b.vScroller._lock=1);e=b.focus.enabled;b.focus.enabled=
0;b.body.refresh().then(function(){b.vScroller._lock=0;b.view.paging=a._paging;setTimeout(function(){k.add(f,"gridxSlideRefresh");k.add(g,"gridxSlideRefresh");b.vScroller._scrollable&&b.vScroller._scrollable.scrollTo({x:0});c();a._contextNode.style.postion="absolute";setTimeout(function(){a._onTransitionEnd();b.vLayout.reLayout();b.focus.enabled=e;b.body._focusCellRow=0;b.body._focusCellCol=0;b.focus.focusArea("body");a.onFinish(d);a._contextNode.style.postion="relative"},700)},10)})}})});
//# sourceMappingURL=Layer.js.map