//>>built
define("gridx/modules/RowHeader","dojo/_base/declare ../support/query dojo/_base/lang dojo/_base/sniff dojo/aspect dojo/dom-construct dojo/dom-class dojo/dom-style dojo/dom-geometry dojo/keys ../core/_Module".split(" "),function(r,f,n,l,p,g,h,k,q,m,s){return r(s,{name:"rowHeader",constructor:function(){this.headerNode=g.create("div",{"class":"gridxRowHeaderHeader",role:"row",innerHTML:'\x3ctable role\x3d"presentation" border\x3d"0" cellspacing\x3d"0" cellpadding\x3d"0" style\x3d"width: 100%;"\x3e\x3ctr\x3e\x3ctd class\x3d"gridxRowHeaderHeaderCell" role\x3d"rowheader" tabindex\x3d"-1"\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e'});
this.bodyNode=g.create("div",{"class":"gridxRowHeaderBody"})},destroy:function(){this.inherited(arguments);g.destroy(this.headerNode);g.destroy(this.bodyNode)},preload:function(){var a=this.headerNode,b=this.bodyNode,c=this.grid,d=c.body,e=this.arg("width");c._initEvents(["RowHeaderHeader","RowHeaderCell"],c._eventNames);c.header.domNode.appendChild(a);a.style.width=e;this.headerCellNode=f("td",a)[0];c._connectEvents(a,"_onHeaderMouseEvent",this);c.mainNode.appendChild(b);b.style.width=e;c.hLayout.register(null,
b);this.batchConnect([d,"onRender","_onRendered"],[d,"onAfterRow","_onAfterRow"],[d,"onAfterCell","_onAfterCell"],[d,"onUnrender","_onUnrender"],[d,"onEmpty",function(){b.innerHTML=""}],[c.bodyNode,"onscroll","_onScroll"],[c,"onRowMouseOver","_onRowMouseOver"],[c,"onRowMouseOut","_onRowMouseOver"],[c,"_onResizeEnd","_onResize"],c.columnWidth&&[c.columnWidth,"onUpdate","_onResize"],c.columnResizer&&[c.columnResizer,"onResize","_onResize"],[c,"onRowHeaderCellMouseOver","_onCellMouseOver"],[c,"onRowHeaderCellMouseOut",
"_onCellMouseOver"],[this.model,"onSizeChange","_onSizeChange"]);this._cnnts.push(p.before(d,"renderRows",n.hitch(this,this._onRenderRows),!0),p.before(d,"_onDelete",n.hitch(this,this._onDelete),!0));c._connectEvents(b,"_onBodyMouseEvent",this);this._initFocus()},load:function(a,b){var c=this,d=c.grid,e=c.bodyNode;b.then(function(){var a=e.offsetWidth||k.get(e,"width"),b=d.isLeftToRight(),f=q.getBorderExtents(d.mainNode);e.style[b?"left":"right"]=-(a+(b?f.l:f.r))+"px";c.loaded.callback()})},width:"20px",
onMoveToRowHeaderCell:function(){},_onRenderRows:function(a,b,c){var d=this.bodyNode;0<b?(a=this._buildRows(a,b),"top"==c?g.place(a,d,"first"):"bottom"==c?g.place(a,d,"last"):(d.innerHTML=a,d.scrollTop=0)):"top"!=c&&"bottom"!=c&&(d.innerHTML="")},_onAfterRow:function(a){var b=a.visualIndex(),c=f('[visualindex\x3d"'+b+'"].gridxRowHeaderRow',this.bodyNode)[0],b=this.grid.dod?f('[visualindex\x3d"'+b+'"].gridxRow',this.grid.bodyNode)[0]:f('[visualindex\x3d"'+b+'"].gridxRow .gridxRowTable',this.grid.bodyNode)[0],
d=this.arg("cellProvider");c.setAttribute("rowid",a.id);c.setAttribute("rowindex",a.index());c.setAttribute("parentid",this.model.treePath(a.id).pop()||"");d&&(c.firstChild.firstChild.firstChild.firstChild.innerHTML=d.call(this,a));this._syncRowHeight(c,b)},_onAfterCell:function(a){var b=a.row.visualIndex();a=f('[visualindex\x3d"'+b+'"].gridxRowHeaderRow',this.bodyNode)[0];b=f('[visualindex\x3d"'+b+'"].gridxRow .gridxRowTable',this.grid.bodyNode)[0];this._syncRowHeight(a,b)},_syncRowHeight:function(a,
b){function c(){return 8>=l("ie")||d._isCollapse?b.offsetHeight+"px":k.getComputedStyle(b).height}var d=this;if(void 0===d._isCollapse){var e=f(".gridxCell",d.grid.header.innerNode)[0];d._isCollapse=e&&"collapse"==k.get(e,"borderCollapse")}a.style.height=a.firstChild.style.height=c();setTimeout(function(){a&&a.firstChild&&(a.style.height=a.firstChild.style.height=c())},0)},_onRendered:function(a,b){var c=this.arg("headerProvider");c&&(this.headerCellNode.innerHTML=c());this._onScroll()},_onSizeChange:function(a,
b){var c=this.arg("headerProvider");!a&&c&&(this.headerCellNode.innerHTML="");this._onScroll()},_onDelete:function(a){var b=this.model.isId(a)&&f('[rowid\x3d"'+this.grid._escapeId(a)+'"].gridxRowHeaderRow',this.bodyNode);if(b&&b.length){var c=b[b.length-1],b=c.getAttribute("parentid"),d={},e=1;d[a]=1;for(a=c.nextSibling;a&&d[a.getAttribute("parentid")];a=a.nextSibling)c=a.getAttribute("rowid"),e++,d[c]=1;for(;a;a=a.nextSibling)a.getAttribute("parentid")==b&&a.setAttribute("rowindex",parseInt(a.getAttribute("rowindex"),
10)-1),d=parseInt(a.getAttribute("visualindex"),10),a.setAttribute("visualindex",d-e)}},_onUnrender:function(a,b,c){!this.model.isId(a)&&c?"post"===c?this.bodyNode.lastChild&&g.destroy(this.bodyNode.lastChild):this.bodyNode.firstChild&&g.destroy(this.bodyNode.firstChild):"refresh"!=b&&(a=this.model.isId(a)&&f('[rowid\x3d"'+this.grid._escapeId(a)+'"].gridxRowHeaderRow',this.bodyNode))&&a.length&&g.destroy(a[a.length-1])},_onScroll:function(){var a=this;a.bodyNode.scrollTop=a.grid.bodyNode.scrollTop;
a.bodyNode.scrollHeight-a.bodyNode.clientHeight>=a.grid.bodyNode.scrollTop?a.bodyNode.scrollTop=a.grid.bodyNode.scrollTop:setTimeout(function(){a.bodyNode.scrollTop=a.grid.bodyNode.scrollTop},0)},_onResize:function(){for(var a=l("ie")?l("ie"):l("trident")?11:!1,b,c=this.grid.bodyNode.firstChild,d=this.bodyNode.firstChild;c&&d;c=c.nextSibling,d=d.nextSibling)b=this.grid.dod?c:c.firstChild,b=8<a?k.getComputedStyle(b).height:b.offsetHeight+"px",d.style.height=d.firstChild.style.height=b;b=this.bodyNode;
d=this.grid;a=b.offsetWidth||k.get(b,"width");c=d.isLeftToRight();d=q.getBorderExtents(d.mainNode);b.style[c?"left":"right"]=-(a+(c?d.l:d.r))+"px"},_buildRows:function(a,b){for(var c=[],d=0;d<b;++d)c.push('\x3cdiv class\x3d"gridxRowHeaderRow" role\x3d"row" visualindex\x3d"',a+d,'"\x3e\x3ctable role\x3d"presentation" border\x3d"0" cellspacing\x3d"0" cellpadding\x3d"0" style\x3d"height: 24px;"\x3e\x3ctr\x3e\x3ctd class\x3d"gridxRowHeaderCell" role\x3d"rowheader" tabindex\x3d"-1"\x3e\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e\x3c/div\x3e');
return c.join("")},_onHeaderMouseEvent:function(a,b){var c=this.grid,d="onRowHeaderHeader"+a;if(c._isConnected(d))c[d](b)},_onBodyMouseEvent:function(a,b){var c=this.grid,d="onRowHeaderCell"+a,e="onRow"+a,f=c._isConnected(d),g=c._isConnected(e);if(f||g)if(this._decorateBodyEvent(b),0<=b.rowIndex){if(b.isRowHeader&&f)c[d](b);if(g)c[e](b)}},_decorateBodyEvent:function(a){for(var b=a.target||a.originalTarget;b&&b!=this.bodyNode;){if(h.contains(b,"gridxRowHeaderCell"))a.isRowHeader=!0,a.rowHeaderCellNode=
b;else if("div"===b.tagName.toLowerCase()&&h.contains(b,"gridxRowHeaderRow")){a.rowId=b.getAttribute("rowid");a.parentId=b.getAttribute("parentid");a.rowIndex=parseInt(b.getAttribute("rowindex"),10);a.visualIndex=parseInt(b.getAttribute("visualindex"),10);break}b=b.parentNode}},_onRowMouseOver:function(a){var b=f('\x3e [rowid\x3d"'+this.grid._escapeId(a.rowId)+'"].gridxRowHeaderRow',this.bodyNode)[0];b&&h.toggle(b,"gridxRowOver","mouseover"==a.type.toLowerCase())},_onCellMouseOver:function(a){var b=
f('\x3e [rowid\x3d"'+this.grid._escapeId(a.rowId)+'"].gridxRowHeaderRow .gridxRowHeaderCell',this.bodyNode)[0];b&&h.toggle(b,"gridxRowHeaderCellOver","mouseover"==a.type.toLowerCase())},_initFocus:function(){var a=this.grid.focus;a&&a.registerArea({name:"rowHeader",priority:0.9,focusNode:this.bodyNode,scope:this,doFocus:this._doFocus,onFocus:this._onFocus,doBlur:this._blur,onBlur:this._blur,connects:[this.connect(this.bodyNode,"onkeydown","_onKeyDown")]})},_doFocus:function(a){if(this._focusRow(this.grid.body._focusCellRow))return this.grid.focus.stopEvent(a),
!0},_onFocus:function(a){for(a=a.target;a!=this.bodyNode;){if(h.contains(a,"gridxRowHeaderRow"))return a=this.grid.body._focusCellRow=parseInt(a.getAttribute("visualindex"),10),this._focusRow(a),this._onScroll(),!0;a=a.parentNode}},_focusRow:function(a){a=f('[visualindex\x3d"'+a+'"] .gridxRowHeaderCell',this.bodyNode)[0];this._blur();if(a=a||this.bodyNode.firstChild)h.add(a,"gridxCellFocus"),a.focus();return a},_blur:function(){f(".gridxCellFocus",this.bodyNode).forEach(function(a){h.remove(a,"gridxCellFocus")});
return!0},_onKeyDown:function(a){var b=this,c=b.grid;if(!b._busy&&"rowHeader"==c.focus.currentArea()&&a.keyCode==m.UP_ARROW||a.keyCode==m.DOWN_ARROW){c.focus.stopEvent(a);var d=c.body,e=d._focusCellRow+(a.keyCode==m.UP_ARROW?-1:1);d._focusCellRow=e=0>e?0:e>=c.view.visualCount?c.view.visualCount-1:e;b._busy=1;c.vScroller.scrollToRow(e).then(function(){b._focusRow(e);b._busy=0;b.onMoveToRowHeaderCell(e,a)})}}})});
//# sourceMappingURL=RowHeader.js.map