//>>built
require({cache:{"url:gridx/templates/FilterBar.html":'\x3cinput type\x3d"button" data-dojo-type\x3d"dijit.form.Button" data-dojo-props\x3d"\n\ticonClass: \'gridxFilterBarBtnIcon\',\n\tlabel: \'...\',\n\ttitle: \x26quot;${defineFilter}\x26quot;" aria-label\x3d"${defineFilter}"\n/\x3e\x3cdiv class\x3d"gridxFilterBarStatus"\n\t\x3e\x3cspan\x3e${noFilterApplied}\x3c/span\n\t\x3e\x3cspan class\x3d"gridxFilterBarCloseBtn" tabindex\x3d"-1" title\x3d"${closeFilterBarBtn}" role\x3d"button"\x3e\x3cspan class\x3d"gridxFilterBarCloseBtnText"\x3ex\x3c/span\x3e\x3c/span\n\x3e\x3c/div\x3e\n'}});
define("gridx/modules/filter/FilterBar","dojo/_base/kernel dojo/_base/declare dijit/registry dojo/_base/lang dojo/_base/array dojo/_base/event dojo/dom-construct dojo/dom-attr dojo/dom-class dojo/string dojo/parser dojo/query dojo/keys dojo/on dojox/html/entities dijit/_BidiSupport ../../core/_Module dojo/text!../../templates/FilterBar.html ../Filter ./FilterDialog ./FilterConfirmDialog ./FilterTooltip dijit/TooltipDialog dijit/popup dijit/form/Button".split(" "),function(F,u,v,m,k,n,p,q,r,s,w,h,
t,x,y,z,A,B,d,C,D,E){return u(A,{name:"filterBar",forced:["filter"],preload:function(){var a=this,b=a.grid,c;b.persist&&(c=b.persist.registerAndLoad("filterBar",function(){return a.filterData}));c?a.filterData=c:c=a.arg("filterData");c&&b.filter.setFilter(a._createFilterExpr(c),1)},closeButton:!0,defineFilterButton:!0,tooltipDelay:300,maxRuleCount:0,ruleCountToConfirmClearFilter:2,conditions:{string:"contain equal startWith endWith notEqual notContain notStartWith notEndWith isEmpty".split(" "),number:"equal greater less greaterEqual lessEqual notEqual isEmpty".split(" "),
date:["equal","before","after","range","isEmpty"],time:["equal","before","after","range","isEmpty"],"enum":["equal","notEqual","isEmpty"],"boolean":["equal","isEmpty"]},load:function(a,b){d.before=d.lessEqual;d.after=d.greaterEqual;this._nls=this.grid.nls;this.domNode=p.create("div",{innerHTML:s.substitute(B,this._nls),"class":"gridxFilterBar"});w.parse(this.domNode);r.toggle(this.domNode,"gridxFilterBarHideCloseBtn",!this.arg("closeButton"));this.grid.vLayout.register(this,"domNode","headerNode",
-0.5);this._initWidgets();this._initFocus();this.refresh();this.connect(this.domNode,"onclick","onDomClick");this.connect(this.domNode,"onmouseover","onDomMouseOver");this.connect(this.domNode,"onmousemove","onDomMouseMove");this.connect(this.domNode,"onmouseout","onDomMouseOut");this.aspect(this.grid.model,"setStore",function(){this.filterData=null;this._buildFilterState()});this.loaded.callback()},onDomClick:function(a){a.target&&a.target.tagName&&("clear"===q.get(a.target,"action")?this.clearFilter():
r.contains(a.target,"gridxFilterBarCloseBtn")||r.contains(a.target,"gridxFilterBarCloseBtnText")?this.hide():this.showFilterDialog())},onDomMouseMove:function(a){(!a||!a.target||!("clear"===q.get(a.target,"action")||this.btnFilter===dijit.getEnclosingWidget(a.target)))&&this._showTooltip(a)},onDomMouseOver:function(a){},onDomMouseOut:function(a){window.setTimeout(m.hitch(this,"_hideTooltip"),10)},_createFilterExpr:function(a){var b=[];k.forEach(a.conditions,function(a){var e="string";if(a.colId)e=
this.grid.column(a.colId).dataType(),b.push(this._getFilterExpression(a.condition,a,e,a.colId));else{var f=[];k.forEach(this.grid.columns(),function(b){b.isFilterable()&&f.push(this._getFilterExpression(a.condition,a,e,b.id))},this);b.push(d.or.apply(d,f))}},this);return("all"===a.type?d.and:d.or).apply(d,b)},applyFilter:function(a){var b=this,c=this._createFilterExpr(a);this.filterData=a;this.grid.filter.setFilter(c);this.model.when({}).then(function(){b._currentSize=b.model.size();b._totalSize=
0<=b.model._cache.totalSize?b.model._cache.totalSize:b.model._cache.size();b._buildFilterState()})},confirmToExecute:function(a,b){var c=this.arg("ruleCountToConfirmClearFilter");this.filterData&&(this.filterData.conditions.length>=c||0>=c)?(this._cfmDlg||(this._cfmDlg=new D({grid:this.grid})),this._cfmDlg.execute=m.hitch(b,a),this._cfmDlg.show()):a.apply(b)},clearFilter:function(a){a?(this.filterData=null,this.grid.filter.clearFilter(),this._buildFilterState()):this.confirmToExecute(m.hitch(this,
"clearFilter",!0),this)},columnMixin:{isFilterable:function(){return!1!==this.grid._columnsById[this.id].filterable},setFilterable:function(a){this.grid.filterBar._setFilterable(this.id,a);return this},dataType:function(){return(this.grid._columnsById[this.id].dataType||"string").toLowerCase()},filterConditions:function(){return this.grid.filterBar._getColumnConditions(this.id)}},refresh:function(){this.btnClose.style.display=this.closeButton?"":"none";this.btnFilter.domNode.style.display=this.arg("defineFilterButton")?
"":"none";this._currentSize=this.model.size();this._totalSize=0<=this.model._cache.totalSize?this.model._cache.totalSize:this.model._cache.size();this._buildFilterState()},isVisible:function(){return"none"!=this.domNode.style.display},show:function(){this.domNode.style.display="block";this.grid.vLayout.reLayout();this.onShow()},hide:function(){this.domNode.style.display="none";this.grid.vLayout.reLayout();this._hideTooltip();this.onHide()},onShow:function(){},onHide:function(){},showFilterDialog:function(){var a=
this._filterDialog;a||(this._filterDialog=a=new C({grid:this.grid}));a.open||(this.filterData||a.setData(this.filterData),a.show(),this.filterData&&a.setData(this.filterData))},uninitialize:function(){this._filterDialog&&this._filterDialog.destroyRecursive();this.inherited(arguments);p.destroy(this.domNode)},_getColumnConditions:function(a){var b;a?(b=this.grid._columnsById[a].disabledConditions||[],a=(this.grid._columnsById[a].dataType||"string").toLowerCase()):(b=[],a="string");a=this.conditions[a];
var c={};a||(a=this.conditions.string);k.forEach(b,function(a){c[a]=!0});return a=k.filter(a,function(a){return!c[a]})},_setFilterable:function(a,b){var c=this.grid._columnsById[a];if(c&&c.filterable!=!!b&&(c.filterable=!!b,this.filterData)){var c=this.filterData,e=c.conditions.length;c.conditions=k.filter(c.conditions,function(b){return b.colId!=a});e!=c.conditions.length&&this.applyFilter(c);this._filterDialog.open&&this._filterDialog.setData(c)}},_initWidgets:function(){this.btnFilter=v.byNode(h(".dijitButton",
this.domNode)[0]);this.btnClose=h(".gridxFilterBarCloseBtn",this.domNode)[0];this.connect(this.btnClose,"onkeydown","_onCloseKey");this.statusNode=h(".gridxFilterBarStatus",this.domNode)[0].firstChild;q.remove(this.btnFilter.focusNode,"aria-labelledby")},_buildFilterState:function(){var a,b=this;!this.filterData||!this.filterData.conditions.length?(this.statusNode.innerHTML=this.arg("noFilterMessage",this.grid.nls.filterBarMsgNoFilterTemplate),(a=dojo.query("[role]",this.statusNode)[0])&&a.signal.remove()):
(this.statusNode.innerHTML=s.substitute(this.arg("hasFilterMessage",this.arg("useShortMessage")?this.grid.nls.summary:this.grid.nls.filterBarMsgHasFilterTemplate),[this._currentSize,this._totalSize,this.arg("itemsName")?this.arg("itemsName"):this.grid.nls.defaultItemsName])+'\x26nbsp; \x26nbsp; \x3ca action\x3d"clear" tabindex\x3d"-1" role\x3d"button" title\x3d"'+this.grid.nls.filterBarClearButton+'"\x3e'+this.grid.nls.filterBarClearButton+"\x3c/a\x3e",a=dojo.query("[role]",this.statusNode)[0],a.signal=
x(a,"keypress",function(a){a.keyCode===t.ENTER&&b.clearFilter()}),this._buildTooltip())},_buildTooltip:function(){this._tooltip||(this._tooltip=new E({grid:this.grid}));this._tooltip.buildContent()},_showTooltip:function(a,b){this._hideTooltip();this.filterData&&(this.filterData.conditions&&this.filterData.conditions.length)&&(b?this._tooltip.show(a):this._pointTooltipDelay=window.setTimeout(m.hitch(this,"_showTooltip",a,!0),this.arg("tooltipDelay")))},_hideTooltip:function(){var a=this._tooltip;
a&&!a.isMouseOn&&(this._pointTooltipDelay&&(window.clearTimeout(this._pointTooltipDelay),this._pointTooltipDelay=null),a.hide())},_getRuleString:function(a,b,c){if("isEmpty"==a)b="";else if(/^date|^time/i.test(c)){var e=this._formatDate;/^time/i.test(c)&&(e=this._formatTime);"range"===a?(c=this.arg("rangeTemplate",this.grid.nls.rangeTemplate),b=s.substitute(c,[e(b.start),e(b.end)])):b=e(b)}this.grid.textDir&&(e=this.grid.textDir,"auto"==e&&(e=z.prototype._checkContextual(b)),b='\x3cspan dir\x3d"'+
e+'"\x3e'+b+"\x3c/span\x3e");return'\x3cspan style\x3d"font-style:italic"\x3e'+this._getConditionDisplayName(a)+"\x3c/span\x3e "+b},_getConditionDisplayName:function(a){a=a.charAt(0).toUpperCase()+a.substring(1);return this.arg("condition"+a,this.grid.nls["condition"+a])},_getConditionOptions:function(a){var b=this._conditionOptions=this._conditionOptions||{};if(!b[a]){var c=[];k.forEach(this._getColumnConditions(a),function(a){var b=a.charAt(0).toUpperCase()+a.substring(1);c.push({label:this.arg("condition"+
b,this.grid.nls["condition"+b]),value:a})},this);b[a]=c}return b[a]},_getFilterExpression:function(a,b,c,e){a=b.value;var f=this.grid._columnsById[e],k=this.grid.filter.arg("caseSensitive"),h=f.dateParser||this._stringToDate,l=f.timeParser||this._stringToTime,l={custom:f.dataTypeArgs&&f.dataTypeArgs.converter&&m.isFunction(f.dataTypeArgs.converter)?f.dataTypeArgs.converter:null,date:h,time:l},g=b.condition,h=!1;c="isEmpty"==g?"string":c;l=l.custom?l.custom:l[c];!0===f.encode&&"string"===typeof b.value&&
(a=y.encode(b.value));"range"===g?(a=d.value(b.value.start,c),b=d.value(b.value.end,c),c=d.column(e,c,l),c=d.and(d.greaterEqual(c,a),d.lessEqual(c,b))):(/^not/.test(g)&&(h=!0,g=g.replace(/^not/g,""),g=g.charAt(0).toLowerCase()+g.substring(1)),c=d[g](d.column(e,c,l),"isEmpty"==g?null:d.value(a,c),k),h&&(c=d.not(c)));return c},_stringToDate:function(a){if(a instanceof Date)return a;/(\d{4})\/(\d\d?)\/(\d\d?)/.test(a);a=new Date;a.setFullYear(parseInt(RegExp.$1));a.setMonth(parseInt(RegExp.$2)-1);return a},
_stringToTime:function(a){if(a instanceof Date)return a;/(\d\d?):(\d\d?):(\d\d?)/.test(a);a=new Date;a.setHours(parseInt(RegExp.$1));a.setMinutes(parseInt(RegExp.$2));a.setSeconds(parseInt(RegExp.$3));return a},_formatDate:function(a){var b=a.getMonth()+1,c=a.getDate();return b+"/"+c+"/"+a.getFullYear()},_formatTime:function(a){var b=a.getHours();a=a.getMinutes();10>b&&(b="0"+b);10>a&&(a="0"+a);return b+":"+a+":00"},_initFocus:function(){var a=this.grid.focus;a&&(a.registerArea({name:"filterbar_btn",
priority:-1,focusNode:this.btnFilter.domNode,doFocus:this._doFocusBtnFilter,scope:this}),a.registerArea({name:"filterbar_clear",priority:-0.9,focusNode:this.domNode,doFocus:this._doFocusClearLink,scope:this}),a.registerArea({name:"filterbar_close",priority:-0.8,focusNode:this.btnClose,doFocus:this._doFocusBtnClose,scope:this}))},_doFocusBtnFilter:function(a){this.btnFilter.focus();a&&n.stop(a);return!0},_doFocusClearLink:function(a){this.btnFilter.focus();var b=h('a[action\x3d"clear"]')[0];return b?
(b.focus(),a&&n.stop(a),!0):!1},_doFocusBtnClose:function(a){this.btnClose.focus();a&&n.stop(a);return!0},_doBlur:function(){return!0},_onCloseKey:function(a){a.keyCode===t.ENTER&&this.hide()},destroy:function(){this._filterDialog&&this._filterDialog.destroy();this._cfmDlg&&this._cfmDlg.destroy();this.btnFilter.destroy();this._tooltip&&this._tooltip.destroy();p.destroy(this.domNode);this.inherited(arguments)}})});
//# sourceMappingURL=FilterBar.js.map