//>>built
define("gridx/core/Core","require dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/Deferred dojo/DeferredList dojo/store/Memory ./model/cache/Async ./model/Model ./Row ./Column ./Cell ./_Module".split(" "),function(q,B,m,k,r,s,t,L,C,u,v,D,E){function F(a){var b={},c,d,e;if(k.isArray(a)){d=0;for(e=a.length;d<e;++d)c=a[d],c.index=d,c.id=c.id||String(d+1),b[c.id]=c}return b}function w(a,b){if(b)for(var c in b){var d=a[c],e=b[c];d&&k.isObject(d)&&!l(d)?w(d,e):a[c]=e}}function G(a){var b=
a.modules,c=b.length,d=[],e,f;for(e=0;e<c;++e){f=b[e];if(x(f))try{f=q(f)}catch(g){console.error(g)}k.isArray(f)?d=d.concat(f):d.push(f)}b=[];c=d.length;for(e=0;e<c;++e){f=d[e];l(f)&&(f={moduleClass:f});if(f){var h=f.moduleClass;if(x(h))try{h=f.moduleClass=q(h)}catch(H){console.error(H)}if(l(h)){b.push(f);continue}}console.error("The "+(e+1-a.coreModules.length)+"-th declared module can NOT be found, please require it before using it:",f)}a.modules=b}function I(a){var b=E._modules;a=a.modules;var c,
d,e,f,g,h,k;for(c=0;c<a.length;++c){f=a[c].moduleClass.prototype;g=(f.forced||[]).concat(f.required||[]);for(d=0;d<g.length;++d){h=g[d];for(e=a.length-1;0<=e&&a[e].moduleClass.prototype.name!==h;--e);0>e&&(b[h]?a.push({moduleClass:b[h]}):(k=1,console.error("Forced/Required dependent module '"+h+"' is NOT found for '"+f.name+"' module.")))}}if(k)throw Error("Some forced/required dependent modules are NOT found.");}function J(a){for(var b=0,c,d={},e=[];c=a.modules[b];++b)d[c.moduleClass.prototype.name]=
c;for(b in d)e.push(d[b]);a.modules=e}function K(a){var b=a.modules,c,d;for(c=b.length-1;0<=c;--c)(d=b[c].moduleClass.prototype.modelExtensions)&&[].push.apply(a.modelExtensions,d)}function y(a,b,c,d,e,f){var g=d||0;d=0<=e?d+e:b;for(e=[];g<d&&g<b;++g)e.push(a[c](g,0,f));return e}function n(a,b,c){var d,e=a._modules;for(d in e)d=e[d].mod,a=d[c+"Mixin"],l(a)&&(a=a.apply(d)),k.mixin(b,a||{});return b}function z(a,b,c){var d=a._modules,e=d[c],f=e.mod,g=f.loaded;e.done||(e.done=1,(new s(m.map(m.filter(e.deps,
function(a){return d[a]}),A(a,z,a,b)),0,1)).then(function(){f.load?f.load(e.args,b):0>g.fired&&g.callback()}));return g}var p=k.delegate,l=k.isFunction,x=k.isString,A=k.hitch;return B([],{setStore:function(a){this.store!==a&&(this.store=a,this.model.setStore(a))},setData:function(a,b){var c;this.model.setData(a);b||(c=this.model._parseStructure(a),this.setColumns(c))},setColumns:function(a){this.structure=a;this._columns=m.map(a,function(a){return k.mixin({},a)});this._columnsById=F(this._columns);
this.edit&&this.edit._init();if(this.model)this.model._cache.onSetColumns(this._columnsById)},row:function(a,b,c){"number"===typeof a&&!b&&(a=this.model.indexToId(a,c));return this.model.byId(a)?(this._rowObj=this._rowObj||n(this,new u(this),"row"),p(this._rowObj,{id:a})):null},column:function(a,b){var c,d,e={};"number"===typeof a&&!b&&(a=(c=this._columns[a])&&c.id);if(c=this._columnsById[a]){this._colObj=this._colObj||n(this,new v(this),"column");for(d in c)void 0===this._colObj[d]&&(e[d]=c[d]);
return p(this._colObj,e)}return null},cell:function(a,b,c,d){if(a=a instanceof u?a:this.row(a,c,d))if(b=b instanceof v?b:this.column(b,c))return this._cellObj=this._cellObj||n(this,new D(this),"cell"),p(this._cellObj,{row:a,column:b});return null},columnCount:function(){return this._columns.length},rowCount:function(a){return this.model.size(a)},columns:function(a,b){return y(this,this._columns.length,"column",a,b)},rows:function(a,b,c){return y(this,this.rowCount(c),"row",a,b,c)},onModulesLoaded:function(){},
_init:function(){var a=this,b,c=a._deferStartup=new r;a.modules=a.modules||[];a.modelExtensions=a.modelExtensions||[];a.touch?a.touchModules&&(a.modules=a.modules.concat(a.touchModules)):a.desktopModules&&(a.modules=a.modules.concat(a.desktopModules));b=a.store?a.store:a._parseData(a.data);r.when(b,function(){a.setColumns(a.structure);G(a);I(a);J(a);K(a);a.model=new C(a);a.when=A(a.model,a.model.when);a._create();a._preload();a._load(c).then(function(){a.onModulesLoaded()})})},_uninit:function(){var a=
this._modules,b;for(b in a)a[b].mod.destroy();this.model&&this.model.destroy()},_create:function(){for(var a=0,b,c=this._modules={};b=this.modules[a];++a){var d;d=b.moduleClass;var e=d.prototype.name;if(!c[e]){var f=c,g=b,h=d=new d(this,b);b=b.moduleClass.prototype;b=(b.forced||[]).concat(b.optional||[]);f[e]={args:g,mod:h,deps:b};d.getAPIPath&&w(this,d.getAPIPath())}}},_preload:function(){var a,b=this._modules;for(a in b)a=b[a],a.mod.preload&&a.mod.preload(a.args)},_load:function(a){var b=[],c;for(c in this._modules)b.push(z(this,
a,c));return new s(b,0,1)},_defaultData:[{id:1,name:"Dojo"},{id:2,name:"jQuery"},{id:3,name:"ExtJS"},{id:4,name:"YUI"}],_parseData:function(a){this.store="object"===typeof a&&a.constructor===Array?new t({data:a}):new t({data:this._defaultData});this.structure||(this.structure=this._parseStructure(a));return 1},_parseStructure:function(a){if(!a||"object"!==typeof a)return[{id:1,name:"id",field:"id"},{id:2,name:"name",field:"name"}];var b={},c=a.length,d,e,f,g,h,k=[];for(e=0;e<c;e++){d=Object.keys(a[e]);
g=d.length;for(f=0;f<g;f++)b[d[f]]=1}for(h in b)k.push({id:h,name:h,field:h});return k}})});
//# sourceMappingURL=Core.js.map