//>>built
define("gridx/core/model/extensions/ClientFilter",["dojo/_base/declare","dojo/_base/array","dojo/_base/lang","dojo/_base/Deferred","../_Extension"],function(s,g,n,p,t){var q=n.hitch,m=g.forEach,r=g.indexOf;return s(t,{name:"clientFilter",priority:20,constructor:function(a,b){this.pageSize=b.pageSize||100;this._mixinAPI("filter","hasFilter");a.onFilterProgress=function(){};this.aspect(a,"_msg","_receiveMsg");this.aspect(a,"setStore","clear")},clear:function(){this._ids=0;this._indexes={};this._struct=
{};this._struct[""]=[]},filter:function(a){this.model._addCmd({name:"_cmdFilter",scope:this,args:arguments,async:1})},hasFilter:function(){return!!this._ids},hasChildren:function(a){var b=this.inner;return this._ids?!1:b._call("hasChildren",arguments)},byIndex:function(a,b){var c=this._ids,d=this.inner,f=c&&c[a];return!this.model.isId(b)&&c?this.model.isId(f)&&d._call("byId",[f]):d._call("byIndex",arguments)},byId:function(a){return this.ids&&void 0===this._indexes[a]?null:this.inner._call("byId",
arguments)},indexToId:function(a,b){return!this.model.isId(b)&&this._ids?this._ids[a]:this.inner._call("indexToId",arguments)},idToIndex:function(a){if(this._ids&&""===this.inner._call("parentId",arguments)){var b=r(this._ids,a);return 0<=b?b:void 0}return this.inner._call("idToIndex",arguments)},size:function(a){return!this.model.isId(a)&&this._ids?this._ids.length:this.inner._call("size",arguments)},when:function(a,b){var c=this,d=function(){c._ids&&c._mapWhenArgs(a);return c.inner._call("when",
[a,b])};if(c._refilter&&(c._refilter=0,c._ids)){var f=new p;c._reFilter().then(function(){d().then(q(f,f.callback),q(f,f.errback))});return f}return d()},_cmdFilter:function(){var a=arguments;return this._filter.apply(this,a[a.length-1])},_filter:function(a){var b=this;b.size();var c=b.model;b.clear();if(n.isFunction(a)){var d=[],f=function(e,k,l){if(!e.length)return!1;var h,g;e=k+e.length;for(l=void 0!==l?l:"";k<e;++k)if(h=b.indexToId(k,l),g=b.byIndex(k,l))a(g,h)&&(d.push(h),b._indexes[h]=k),h=c.children(h),
h.length&&(g=c.parentId(h[0]),f(h,0,g));else break};return b.model.scan({start:0,pageSize:b.pageSize,whenScope:b,whenFunc:b.when},f).then(function(){d.length==b.size()?b.clear():(b._ids=d,b.model._msg("filter",d))},0,b.model.onFilterProgress)}var e=new p;e.callback();return e},_mapWhenArgs:function(a){var b=this,c=[],d=b._ids.length;a.id=g.filter(a.id,function(a){return void 0!==b._indexes[a]});m(a.range,function(a){if(b.model.isId(a.parentId))c.push(a);else{if(!a.count||0>a.count){var e=d-a.start;
if(0>=e)return;a.count=e}for(e=0;e<a.count;++e){var g=b._mapIndex(e+a.start);void 0!==g&&c.push({start:g,count:1})}}});a.range=c},_mapMoveArgs:function(a){var b=this;if(3==a.length){for(var c=[],d=a[0],f=a[0]+a[1];d<f;++d)c.push(b._mapIndex(d));a[0]=c;a[1]=b._mapIndex(a[2]);a.pop()}else a[0]=g.map(a[0],function(a){return b._mapIndex(a)}),a[1]=b._mapIndex(a[1])},_mapIndex:function(a){return this._indexes[this._ids[a]]},_moveFiltered:function(a,b,c){var d=this._ids.length;if(0<=a&&a<d&&0<b&&Infinity>
b&&0<=c&&c<d&&(c<a||c>a+b)){var f=[],d=a;for(a+=b;d<a;++d)f.push(this._mapIndex(d));this.inner._call("moveIndexes",[f,this._mapIndex(c)])}},_reFilter:function(){var a=this;return a.inner._call("when",[{id:a._ids,range:[]},function(){m(a._ids,function(b){var c=a.inner._call("idToIndex",[b]);a._indexes[b]=c});a._ids.sort(function(b,c){return a._indexes[b]-a._indexes[c]})}])},_onMoved:function(a){var b=this;m(b._ids,function(c){var d=b._indexes[c];void 0!==a[d]&&(b._indexes[c]=a[d])});b._ids.sort(function(a,
d){return b._indexes[a]-b._indexes[d]})},_receiveMsg:function(a,b){this._ids&&("storeChange"==a?this._refilter=1:"moved"==a?this._onMoved(b):"beforeMove"==a&&this._mapMoveArgs(b))},_onNew:function(a){this._ids&&(this._ids.push(a),this._refilter=1);this.onNew.apply(this,arguments)},_onDelete:function(a,b,c){var d=this._indexes,f=this._ids;if(f){var e=r(f,a),g=d[a];0<=e&&f.splice(e,1);if(0<=e&&void 0!==g)for(e in b=e,d)d[e]>g&&--d[e];else b=void 0,this._refilter=1}this.onDelete(a,b,c)}})});
//# sourceMappingURL=ClientFilter.js.map